const IDENTITY = Object.freeze([0, 0, 0, 1]);
const YAW_90 = Object.freeze([0, 0.7071067811865475, 0, 0.7071067811865476]);
const YAW_NEG_90 = Object.freeze([0, -0.7071067811865475, 0, 0.7071067811865476]);
const YAW_180 = Object.freeze([0, 1, 0, 0]);
const UNIT_SCALE = Object.freeze([1, 1, 1]);

function instance(id, assetId, name, room, position, rotation = IDENTITY, scale = UNIT_SCALE) {
  return Object.freeze({ id, assetId, name, room, position, rotation, scale });
}

export const ROOM_GROUPS = Object.freeze([
  ["room-living", "Living Room", "living"],
  ["room-dining", "Dining Room", "dining"],
  ["room-master-bedroom", "Master Bedroom", "master-bedroom"],
  ["room-bedroom-2", "Bedroom 2", "bedroom-2"],
  ["room-kitchen", "Kitchen", "kitchen"],
  ["room-bathroom", "Bathroom", "bathroom"],
  ["room-entry", "Entry", "entry"],
  ["room-corridor", "Corridor", "corridor"],
]);

// Floorplan source (X, Y, Z-up) is authored explicitly here in runtime Y-up coordinates (X, Z, -Y).
export const SMART_HOME_INSTANCES = Object.freeze([
  instance("home-shell", "home_shell", "90 m2 Home Shell", "architecture", [0, 0, 0]),
  instance("entrance-door", "entrance_door", "Entrance Door", "entry", [5.18, 0, 3.55], YAW_180),
  instance(
    "balcony-door",
    "balcony_sliding_door",
    "Balcony Sliding Door",
    "living",
    [-3.8, 0, 3.55],
  ),
  instance("door-living", "interior_door", "Living Room Door", "corridor", [-4.05, 0, 0.46]),
  instance(
    "door-master",
    "interior_door",
    "Master Bedroom Door",
    "corridor",
    [-4.45, 0, -0.8],
    YAW_180,
  ),
  instance(
    "door-bedroom-2",
    "interior_door",
    "Bedroom 2 Door",
    "corridor",
    [-0.05, 0, -0.8],
    YAW_180,
  ),
  instance("door-kitchen", "interior_door", "Kitchen Door", "corridor", [3.45, 0, -0.8], YAW_180),
  instance("door-bathroom", "interior_door", "Bathroom Door", "corridor", [3.43, 0, 0.46]),
  instance(
    "window-master-north",
    "casement_window",
    "Master Bedroom North Window",
    "master-bedroom",
    [-3.65, 0.85, -3.55],
    YAW_180,
  ),
  instance(
    "window-bedroom-2-north",
    "casement_window",
    "Bedroom 2 North Window",
    "bedroom-2",
    [0.1, 0.9, -3.55],
    YAW_180,
  ),
  instance(
    "window-kitchen-north",
    "casement_window",
    "Kitchen North Window",
    "kitchen",
    [4, 1.05, -3.55],
    YAW_180,
  ),
  instance(
    "window-living-west",
    "casement_window",
    "Living Room West Window",
    "living",
    [-5.9, 0.65, 1.8],
    YAW_90,
  ),
  instance(
    "window-master-west",
    "casement_window",
    "Master Bedroom West Window",
    "master-bedroom",
    [-5.9, 0.9, -2.1],
    YAW_90,
  ),
  instance(
    "window-bathroom-east",
    "casement_window",
    "Bathroom East Window",
    "bathroom",
    [5.9, 1.55, 2.1],
    YAW_NEG_90,
  ),
  instance(
    "window-kitchen-east",
    "casement_window",
    "Kitchen East Window",
    "kitchen",
    [5.9, 1.05, -1.95],
    YAW_NEG_90,
  ),

  instance("living-sofa", "sofa_3seat", "Living Room Sofa", "living", [-4.25, 0, 2.2], YAW_90),
  instance(
    "living-coffee-table",
    "coffee_table",
    "Living Room Coffee Table",
    "living",
    [-3.15, 0, 2.15],
  ),
  instance(
    "living-tv-console",
    "tv_console",
    "Living Room TV Console",
    "living",
    [-1.55, 0, 1.95],
    YAW_NEG_90,
  ),
  instance(
    "living-smart-tv",
    "smart_tv",
    "Living Room Smart TV",
    "living",
    [-1.48, 0.85, 1.95],
    YAW_NEG_90,
  ),
  instance(
    "living-air-purifier",
    "air_purifier",
    "Living Room Air Purifier",
    "living",
    [-5.3, 0, 0.85],
    YAW_90,
  ),
  instance(
    "living-ac",
    "wall_air_conditioner",
    "Living Room Air Conditioner",
    "living",
    [-5.72, 2.25, 0.95],
    YAW_90,
  ),
  instance(
    "living-curtain",
    "motorized_curtain",
    "Living Room Motorized Curtain",
    "living",
    [-3.8, 2.62, 3.46],
  ),
  instance(
    "living-ceiling-light",
    "ceiling_light",
    "Living Room Ceiling Light",
    "living",
    [-3.65, 2.72, 2],
  ),

  instance("dining-table", "dining_table", "Dining Table", "dining", [0.45, 0, 2.1]),
  instance(
    "dining-chair-north",
    "dining_chair",
    "Dining Chair North",
    "dining",
    [0.45, 0, 1.35],
    YAW_180,
  ),
  instance("dining-chair-south", "dining_chair", "Dining Chair South", "dining", [0.45, 0, 2.85]),
  instance(
    "dining-chair-west",
    "dining_chair",
    "Dining Chair West",
    "dining",
    [-0.45, 0, 2.1],
    YAW_90,
  ),
  instance(
    "dining-chair-east",
    "dining_chair",
    "Dining Chair East",
    "dining",
    [1.35, 0, 2.1],
    YAW_NEG_90,
  ),
  instance(
    "dining-ceiling-light",
    "ceiling_light",
    "Dining Ceiling Light",
    "dining",
    [0.45, 2.72, 2.1],
  ),

  instance(
    "master-double-bed",
    "double_bed",
    "Master Bedroom Double Bed",
    "master-bedroom",
    [-4.2, 0, -2.45],
    YAW_180,
  ),
  instance(
    "master-bedside-left",
    "bedside_table",
    "Master Bedside Table Left",
    "master-bedroom",
    [-5.25, 0, -2.45],
    YAW_NEG_90,
  ),
  instance(
    "master-bedside-right",
    "bedside_table",
    "Master Bedside Table Right",
    "master-bedroom",
    [-3.15, 0, -2.45],
    YAW_90,
  ),
  instance(
    "master-wardrobe",
    "wardrobe",
    "Master Bedroom Wardrobe",
    "master-bedroom",
    [-1.72, 0, -2.25],
    YAW_NEG_90,
  ),
  instance(
    "master-ac",
    "wall_air_conditioner",
    "Master Bedroom Air Conditioner",
    "master-bedroom",
    [-1.5, 2.57, -2.35],
    YAW_NEG_90,
  ),
  instance(
    "master-curtain",
    "motorized_curtain",
    "Master Bedroom Motorized Curtain",
    "master-bedroom",
    [-3.65, 2.62, -3.46],
    YAW_180,
  ),
  instance(
    "master-ceiling-light",
    "ceiling_light",
    "Master Bedroom Ceiling Light",
    "master-bedroom",
    [-3.62, 2.72, -2.2],
  ),

  instance(
    "bedroom-2-single-bed",
    "single_bed",
    "Bedroom 2 Single Bed",
    "bedroom-2",
    [-0.55, 0, -2.45],
    YAW_180,
  ),
  instance("bedroom-2-desk", "desk", "Bedroom 2 Study Desk", "bedroom-2", [1.35, 0, -3.1], YAW_180),
  instance(
    "bedroom-2-office-chair",
    "office_chair",
    "Bedroom 2 Office Chair",
    "bedroom-2",
    [1.35, 0, -2.4],
  ),
  instance(
    "bedroom-2-ac",
    "wall_air_conditioner",
    "Bedroom 2 Air Conditioner",
    "bedroom-2",
    [2.15, 2.25, -2.25],
    YAW_NEG_90,
  ),
  instance(
    "bedroom-2-curtain",
    "motorized_curtain",
    "Bedroom 2 Motorized Curtain",
    "bedroom-2",
    [0.1, 2.62, -3.46],
    YAW_180,
  ),
  instance(
    "bedroom-2-ceiling-light",
    "ceiling_light",
    "Bedroom 2 Ceiling Light",
    "bedroom-2",
    [0.46, 2.72, -2.2],
  ),

  instance(
    "kitchen-cabinet",
    "kitchen_cabinet",
    "Kitchen Cabinet",
    "kitchen",
    [4.06, 0, -3.15],
    YAW_180,
  ),
  instance(
    "kitchen-refrigerator",
    "smart_refrigerator",
    "Smart Refrigerator",
    "kitchen",
    [5.3, 0, -1.4],
    YAW_NEG_90,
  ),
  instance(
    "kitchen-dishwasher",
    "dishwasher",
    "Dishwasher",
    "kitchen",
    [4.65, 0.006, -3.04],
    YAW_180,
  ),
  instance(
    "kitchen-washer-dryer",
    "washer_dryer",
    "Washer Dryer",
    "kitchen",
    [5.3, 0, -2.35],
    YAW_NEG_90,
  ),
  instance(
    "kitchen-cooktop",
    "induction_cooktop",
    "Induction Cooktop",
    "kitchen",
    [3.35, 0.9, -3.19],
    YAW_180,
  ),
  instance(
    "kitchen-range-hood",
    "smart_range_hood",
    "Smart Range Hood",
    "kitchen",
    [3.35, 1.75, -3.38],
    YAW_180,
  ),
  instance(
    "kitchen-microwave",
    "microwave_oven",
    "Microwave Oven",
    "kitchen",
    [4.2, 1.25, -3.2],
    YAW_180,
  ),
  instance(
    "kitchen-faucet",
    "smart_sink_faucet",
    "Smart Sink Faucet",
    "kitchen",
    [4.85, 0.925, -3.2],
    YAW_180,
  ),
  instance("kitchen-trash-bin", "smart_trash_bin", "Smart Trash Bin", "kitchen", [2.65, 0, -1.35]),
  instance(
    "kitchen-ceiling-light",
    "ceiling_light",
    "Kitchen Ceiling Light",
    "kitchen",
    [4.08, 2.72, -2.15],
  ),

  instance("bathroom-vanity", "bathroom_vanity", "Bathroom Vanity", "bathroom", [3, 0, 0.82]),
  instance(
    "bathroom-ceiling-light",
    "ceiling_light",
    "Bathroom Ceiling Light",
    "bathroom",
    [3.4, 2.72, 2],
  ),

  instance(
    "entry-shoe-cabinet",
    "shoe_cabinet",
    "Entry Shoe Cabinet",
    "entry",
    [5.65, 0, 1.42],
    YAW_NEG_90,
  ),
  instance(
    "entry-door-lock",
    "smart_door_lock",
    "Entry Smart Door Lock",
    "entry",
    [4.82, 1.05, 3.5],
    YAW_180,
  ),
  instance(
    "entry-video-doorbell",
    "video_doorbell",
    "Entry Video Doorbell",
    "entry",
    [4.55, 1.45, 3.74],
    YAW_180,
  ),
  instance(
    "entry-wall-switch",
    "smart_wall_switch",
    "Entry Smart Wall Switch",
    "entry",
    [5.72, 1.3, 3.35],
    YAW_NEG_90,
  ),
  instance(
    "corridor-control-panel",
    "smart_control_panel",
    "Home Control Panel",
    "corridor",
    [5.72, 1.45, -0.2],
    YAW_NEG_90,
  ),

  instance("robot-vacuum", "robot_vacuum", "Robot Vacuum", "corridor", [1.55, 0, 0.05], YAW_90),
  instance(
    "robot-vacuum-dock",
    "robot_vacuum_dock",
    "Robot Vacuum Dock",
    "corridor",
    [2, 0, 0.35],
    YAW_180,
  ),
]);

export const SMART_HOME_VIEWS = Object.freeze([
  Object.freeze({
    id: "whole-home",
    name: "Whole Home",
    position: [11.5, 13, 14],
    target: [0, 0.8, 0],
    fov: 45,
  }),
  Object.freeze({
    id: "living-dining",
    name: "Living And Dining",
    position: [-8.8, 4.5, 8.2],
    target: [-2.2, 0.9, 2],
    fov: 48,
  }),
  Object.freeze({
    id: "bedrooms",
    name: "Bedrooms",
    position: [-7.8, 5.2, -8.8],
    target: [-2, 0.9, -2.2],
    fov: 46,
  }),
  Object.freeze({
    id: "kitchen",
    name: "Kitchen",
    position: [8.6, 4.3, -7],
    target: [4.1, 1, -2.25],
    fov: 44,
  }),
  Object.freeze({
    id: "entry-security",
    name: "Entry Security",
    position: [8.2, 3.2, 6.4],
    target: [5.05, 1.1, 2.7],
    fov: 40,
  }),
]);

export const DEVICE_TARGETS = Object.freeze([
  Object.freeze({
    id: "living-light-status",
    entityId: "living-ceiling-light",
    name: "Living Light Status",
    businessId: "SMART-HOME/LIVING/LIGHT",
    semanticTargetId: "STATE_EMITTER",
    pointer: "/channels/channel-a/status",
    storyState: "normal",
  }),
  Object.freeze({
    id: "living-climate-status",
    entityId: "living-ac",
    name: "Living Climate Status",
    businessId: "SMART-HOME/LIVING/CLIMATE",
    semanticTargetId: "STATE_DISPLAY",
    pointer: "/channels/channel-b/status",
    storyState: "offline",
  }),
  Object.freeze({
    id: "entry-access-status",
    entityId: "entry-door-lock",
    name: "Entry Access Status",
    businessId: "SMART-HOME/ENTRY/ACCESS",
    semanticTargetId: "STATE_LED",
    pointer: "/channels/channel-c/status",
    storyState: "alarm",
  }),
  Object.freeze({
    id: "living-media-status",
    entityId: "living-smart-tv",
    name: "Living Media Status",
    businessId: "SMART-HOME/LIVING/MEDIA",
    semanticTargetId: "STATE_SCREEN",
    pointer: "/channels/channel-a/status",
    storyState: "normal",
  }),
  Object.freeze({
    id: "cleaning-motion-status",
    entityId: "robot-vacuum",
    name: "Cleaning Motion Status",
    businessId: "SMART-HOME/CLEANING/MOTION",
    semanticTargetId: "STATE_MOTION",
    pointer: "/channels/channel-a/status",
    storyState: "normal",
  }),
]);
